// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/reset.go

package models

func (rs *Metrics) Reset() {
	if rs == nil {
		return
	}

	rs.ID = ""

	rs.MType = ""

	if rs.Delta != nil {
		*rs.Delta = 0
	}

	if rs.Value != nil {
		*rs.Value = 0.0
	}

	rs.Hash = ""

}
