package main

import(
	"github.com/rs/zerolog/log"
	"os"
	"go/parser"
	"go/ast"
	"go/types"
	"golang.org/x/tools/go/packages"
	"go/token"
	"path/filepath"
	"text/template"
	"bytes"
	"go/format"
	"fmt"
)

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/reset.go

package {{.Name}}

{{range .Structs}}
func (rs *{{.Name}}) Reset() {
	if rs == nil {
		return
	}
	{{range .Fields}}

	{{ if .Base }}
	{{if .Type.IsPtr }}if rs.{{ .Name }} != nil {
	*{{end}} rs.{{.Name}} = {{ .DefaultValue }}
	{{if .Type.IsPtr }} }{{end}}
	{{end}}
	{{if .Map}}
	clear(rs.{{.Name}})
	{{end}}

	{{if .Slice}}
	rs.{{.Name}} = rs.{{ .Name }}[:0]
	{{end}}
	{{if .Type.IsResetable }}
	{{if .Type.IsPtr}}if rs.{{ .Name}} != nil { {{end}}
		rs.{{ .Name}}.Reset()
	{{if .Type.IsPtr}} }{{end}}
	{{end}}
	{{if .Type.IsInterface}}
	if resetter, ok := rs.{{ .Name}}.(interface{ Reset() }); ok {{if .Type.IsPtr}} && rs.{{ .Name}} != nil {{end}} {
		resetter.Reset()
	}
	{{end}}
	{{end}}
}
{{end}}
`

var primitiveDic = map[string]string {
	"int": "0",
	"int8": "0",
	"int16": "0",
	"int32": "0",
	"int64": "0",
	"uint": "0",
	"uint8": "0",
	"uint16": "0",
	"uint32": "0",
	"uint64": "0",
	"uintptr": "0",
	"float32": "0.0",
	"float64": "0.0",
	"string": "\"\"",
	"complex64": "(0+0i)",
	"complex128": "(0+0i)",
	"bool": "false",
	"rune": "0",
	"byte": "0",
}

type templatePackage struct {
	Name string
	Structs []templateStruct
}

type templateStruct struct {
	Name string
	Fields []templateField
}

type templateField struct {
	Name string
	Type templateFieldType
}

type templateFieldType struct {
	Name string
	IsPtr bool
	IsResetable bool
	IsInterface bool
}

func (tf *templateField) DefaultValue() string {
	val, ok := primitiveDic[tf.Type.Name]
	if ok {
		return val
	}

	return ""
}

func (tf *templateField) Base() int {
	_, ok := primitiveDic[tf.Type.Name]
	if ok {
		return 1
	}
	return 0
}

func (tf *templateField) Slice() int {
	if tf.Type.Name == "Array" {
		return 1
	}
	return 0
}

func (tf *templateField) Map() int {
	if tf.Type.Name == "Map" {
		return 1
	}
	return 0
}

var tmpl = template.Must(template.New("reset").Parse(templateStr))

func main() {
	if len(os.Args) < 2 {
		log.Error().Msg("Укажите путь")
	}
	dirPath := os.Args[1]
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax | packages.NeedImports,
		Env: os.Environ(),
	}

	pkgs, err := packages.Load(cfg, "all")
	if err != nil {
		log.Error().Err(err).Msg("packages error")
		return
	}

	err = readDir(dirPath, func(fname string) error {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, fname, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse file error: %w", err)
		}

		cmap := ast.NewCommentMap(fset, f, f.Comments)

		tP := templatePackage{
			Name: f.Name.Name,
		}

		for n, coms := range cmap {
			for _, gc := range coms {
				for _, c := range gc.List {
					if c.Text == "// generate:reset" {
						if gd, ok := n.(*ast.GenDecl); ok && gd.Tok == token.TYPE {
							for _, spec := range gd.Specs {
								if tspec, ok := spec.(*ast.TypeSpec); ok {
									if strType, ok := tspec.Type.(*ast.StructType); ok {
										var typeStruct templateStruct
										typeStruct.Name = tspec.Name.Name
										for _, field := range strType.Fields.List {
											var typeField templateField
											for _, ident := range field.Names {
												typeField.Name = ident.Name
											}
											switch t := field.Type.(type) {
												case *ast.Ident:
													typeField.Type = templateFieldType{Name: t.Name}
													if t.Name == "any" {
														typeField.Type.IsInterface = true
													}
													searchResetInPkg(pkgs, &typeField, "", t.Name)
												case *ast.SelectorExpr:
													ident, ok := t.X.(*ast.Ident)
													if !ok {
														continue
													}
													typeField.Type = templateFieldType{Name: ident.Name }
													typeField.Type.Name += "." + t.Sel.Name
													searchResetInPkg(pkgs, &typeField, ident.Name, t.Sel.Name)
												case *ast.StarExpr:
													switch tt := t.X.(type) {
														case *ast.Ident:
															typeField.Type = templateFieldType{Name: tt.Name, IsPtr: true }
															searchResetInPkg(pkgs, &typeField, "", tt.Name)
														case *ast.SelectorExpr:
															ident, ok := tt.X.(*ast.Ident)
															if !ok {
																continue
															}
															typeField.Type = templateFieldType{Name: ident.Name, IsPtr: true }
															typeField.Type.Name += "." + tt.Sel.Name
															searchResetInPkg(pkgs, &typeField, ident.Name, tt.Sel.Name)
													}

												case *ast.MapType:
													typeField.Type = templateFieldType{Name: "Map"}

												case *ast.ArrayType:
													typeField.Type = templateFieldType{Name: "Array"}
												case *ast.InterfaceType:
													typeField.Type = templateFieldType{Name: "Interface", IsInterface: true }
											}
											typeStruct.Fields = append(typeStruct.Fields, typeField)
										}

										tP.Structs = append(tP.Structs, typeStruct)

									}

								}
							}
						}
					}
				}
				
			}
		}

		if len(tP.Structs) == 0 {
			return nil
		}

		var buf bytes.Buffer
		err = tmpl.Execute(&buf, tP)
		if err != nil {
			return fmt.Errorf("template execute err: %w", err)
		}

		bufFmt, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("format buf err: %w", err)
		}

		err = os.WriteFile(filepath.Dir(fname) + "/" + "reset.gen.go", bufFmt, 0644)
		if err != nil {
			return fmt.Errorf("write to file err: %w", err)
		}
		return nil
	})
	if err != nil {
		log.Error().Err(err).Msg("reset error")
	}
}

func readDir(path string, fn func(fname string) error) error {
	files, err := os.ReadDir(path)
	if err != nil {
		return err
	}

	for _, f := range files {
		newPath := path + "/" + f.Name()
		if f.IsDir() {
			err := readDir(newPath, fn)
			if err != nil {
				return err
			}
			continue
		}

		if filepath.Ext(f.Name()) != ".go" {
			continue
		}

		fn(newPath)
	}
	return nil
}

func searchResetInPkg(pkgs []*packages.Package, tF *templateField, identName string, selectorName string) {
	for _, pkg := range pkgs {
		for pkgIdent, pkgInfo := range pkg.TypesInfo.Defs {

			if pkgInfo == nil || pkgIdent.Obj == nil || pkgIdent.Obj.Kind != ast.Typ {
				continue
			}

			namedType, ok := pkgInfo.Type().(*types.Named)
			if !ok {
				continue
			}

			if pkgIdent.Name != selectorName || pkg.Name != identName {
				continue
			}

			numM := namedType.NumMethods()

			for i := 0; i < numM; i++ {
				method := namedType.Method(i)
				if method.Name() == "Reset" {
					tF.Type.IsResetable = true
				}
			}
		}
	}
}
